[package]
name = "ch01"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1.40.0", features = ["full"]}
reqwest = { version = "0.11.8", features = ["json"]}
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
